export const SET_STATUS = 'SET_STATUS';
export const PORT_CONNECT = 'PORT_CONNECT';
export const PORT_DISCONNECT = 'PORT_DISCONNECT';
export const PORT_SEND_MESSAGE = 'PORT_SEND_MESSAGE';

export const INJECT_SCRIPT = 'INJECT_SCRIPT';
export const SCRIPT_INJECTED = 'SCRIPT_INJECTED';

export const PORT_CONNECTED = 'PORT_CONNECTED';
export const PORT_DISCONNECTED = 'PORT_DISCONNECTED';

export const SET_STAGE = 'SET_STAGE';
export const TOGGLE_SETTINGS = 'TOGGLE_SETTINGS';
export const SET_ID = 'SET_ID';
export const SET_CONTAINERS = 'SET_CONTAINERS';
export const SET_CONTAINER = 'SET_CONTAINER';
export const SET_CONNECTED = 'SET_CONNECTED';
export const SYNCHRONIZE_STATUS = 'SYNCHRONIZE_STATUS';
